JPERF-214: Use only one license, because these two are colliding
Fix Jira-side errors like:
```
java.lang.IllegalArgumentException: Multiple entries with same key:
jira-software=com.atlassian.jira.license.SubscriptionLicenseDetails@10ca1d5b and jira-software=com.atlassian.jira.license.DefaultLicenseDetails@bdacd99b
```